repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: helm
        args: [--allow-multiple-documents]
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-toml
    -   id: pretty-format-json
    -   id: detect-private-key
-   repo: https://github.com/csachs/pyproject-flake8
    rev: v0.0.1a2.post1
    hooks:
      - id: pyproject-flake8
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
    -   id: isort
