apiVersion: batch/v1
kind: CronJob
metadata:
  name: spotify-playlist-renamer-cronjob
  namespace: spotify-playlist-renamer
spec:
  concurrencyPolicy: Forbid
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          automountServiceAccountToken: false
          containers:
            - name: spotify-playlist-renamer
              image: "{{ if eq .Values.environment "prod" }}{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}{{ else }}localhost:5001/spotify-playlist-renamer{{ end }}"
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: spotify-playlist-renamer-secret-vars
                - configMapRef:
                    name: spotify-playlist-renamer-configmap
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                readOnlyRootFilesystem: true
                runAsUser: 1000
                runAsGroup: 1000
              volumeMounts:
                - name: token
                  mountPath: {{ .Values.cache.folder }}
                  readOnly: false
          volumes:
            - name: token
              persistentVolumeClaim:
                claimName: spotify-playlist-renamer-pvc
          imagePullSecrets:
            - name: github-pull-secret
