apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostdata-pv
spec:
  storageClassName: host
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
    type: Directory
