name: Build and deploy an app to Symbiosis

on:
  push:
    branches:
      - $default-branch
  workflow_dispatch:


jobs:
  build:
    permissions:
      actions: read
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
